### ISSUE TITLE
Real optimization of same size and quality images

### ISSUE THREAD

**Issue by ot2sen** [CiroArtigot/aixeenaseoimages#5]
Have you considered to have a powerful optimization for same size and visual quality, but much less weight/file size?
Perhaps TinyPNG could be optional choise for to add extra power to this tool.
https://tinypng.com/developers

**Comment by CiroArtigot** [comment]
Hello Ole!
I'm going to take a look thanks!
Yes it will be great to have the better optimization working with the plugin!
Thanks!
Ciro

**Comment by CiroArtigot** [comment]
Hello Ole!
I have taked a look to TinyPNG but it´s not the optimization I'm looking for.
I would like to find a good library with a powerful optimization but not by a third, or paid service.
100% code inside the site.
